### ISSUE TITLE
Latest chrome update makes background.js redundant

### ISSUE THREAD

**Issue by Palisar** [MartinWie/DoNotSuspend#1]
I've started to look into ways to access chrome://discards in the new version of chrome, i still havent figured it out, but either way this extension will no longer work in its current state

**Comment by MartinWie** [comment]
Hi, sorry for the late response, can you specify the version of chrome you are referring too?
Half a year later, still no issues with accessing the chrome "chrome://discards/" and disabling the "AutoDiscardable" flag there with the extension still works as expected.
