### ISSUE TITLE
Discard tabs with file:// protocol

### ISSUE THREAD

**Issue by arvabalazs** [MartinWie/DoNotSuspend#2]
Hi

Thank you for the extension!

I would like to discard a tab which is from the filesystem. Can you remove the condition or add file:// too?
https://github.com/MartinWie/DoNotSuspend/blob/77f4b7a012f90bdf1199945585403b6fae210747/background-worker.js#L83

**Comment by MartinWie** [comment]
Hi, you are welcome! 👍 
Not sure if the functionality was clear enough, this plugin is to prevent tabs from automatically discarding. 
It is not for discarding tabs, for this you would need a different extension.

I could also create an extension for suspending tabs, for example, after they were inactive for a specific amount of minutes.

But to come back to your suggestion, removing the check would try to toggle the "AutoDiscardable" flag for all tabs, which causes errors for system tabs.
I will check out the option to add also "file://". 

But to be clear this would only give the option to prevent local file tabs from being discarded, not give the option to discard them, is this what you are trying to achieve ?

Best Martin

**Comment by arvabalazs** [comment]
Hi

Sorry, it was just bad phrasing from my side in the description. I understand what this extension is for. I have a tab, I would like to prevent Chrome (Brave) from suspending its running js.

I do not know why but even if AutoDiscard disabled my file, it is still suspended, so I think I rewrite my application to use a Worker, which (at least theoretically) would solve my problem.

So from my side: please consider this CR as a low priority, even if it makes sense.

BR,
Balázs

**Comment by MartinWie** [comment]
Hi, ok
added the fix 👍 
The update is now in review by the Google team and will be published, as soon as the change is accepted.

For details, check the latest commit :) 
In short, I extended the check to include "file:" as valid.

Hope this helps!

Best
Martin

**Comment by MartinWie** [comment]
fixed

**Comment by MartinWie** [comment]
Btw: If you find this extension useful, please consider giving it a star! :)
