### ISSUE TITLE
How Do I Stop Pages from Re-loading?

### ISSUE THREAD

**Issue by chipsmith** [MartinWie/DoNotSuspend#3]
I added the DoNotDiscard extension because I read I could use it to prevent Facebook from auto-refreshing every time I returned to a tab with it open but I can't figure out how to do it. Could you please tell me how to do that? 

Cheers.

**Comment by MartinWie** [comment]
Hi,
sure thing, but first some basic information: 
- If your device has not enough resources(e.g. RAM) this extension cannot prevent the browser from suspending a tab.
- You can open "chrome://discards/" to see all tabs and their suspension state.(You can also manually set this there)#

Here the part about the extension:
You can just add "facebook.com" without the " you could also just add "facebook". The extension checks if the domain contains one of the added Strings(texts) you added to the list.

I hope this helps and will close the issue and use it to update the existing usage documentation.

Cheers
