### ISSUE TITLE
popup is too narrow

### ISSUE THREAD

**Issue by ApeKattQuest-MonkeyPython** [MartinWie/DoNotSuspend#4]
Please fix size for popup box with settings.
It is so small that it is not usable, and no editing can take place, see attached screen:

![image](https://github.com/user-attachments/assets/6d50f832-d790-4949-88bc-bf19e64f0546)

**Comment by MartinWie** [comment]
Thanks for flagging, damn, that's an old project, I will add some styling and add a minimal width!

Cheers

**Comment by MartinWie** [comment]
What device/browser are you using?

**Comment by MartinWie** [comment]
I worked on a fix yesterday that should be approved by the Google Chrome team soon.

I will close the issue for now.

**Comment by ApeKattQuest-MonkeyPython** [comment]
Thanks! it seems to look much better now!
I'm using Latest Vivaldi.

**Comment by MartinWie** [comment]
Cool thanks for the feedback! 
Cheers!
